fixes

diff --git a/.github/workflows/merge-enforcer.yml b/.github/workflows/merge-enforcer.yml
--- a/.github/workflows/merge-enforcer.yml
+++ b/.github/workflows/merge-enforcer.yml
@@ -14,6 +14,6 @@ jobs:
     runs-on: ubuntu-latest
     if: github.event_name == 'pull_request' && !contains(github.head_ref, 'hotfix-') || github.head_ref != 'develop'
     steps:
-      run: |
-        echo "ERROR: You can only merge to main from dev or hotfix."
-        exit 1
+      - run: |
+          echo "ERROR: You can only merge to main from dev or hotfix."
+          exit 1
